### PR TITLE
Updated sieve_of_eratosthenes.py

### PR DESCRIPTION
**Pull request by vedangmehta**
Added a unit test file and changed the loop to list comprehension.

### CODE REVIEW

**Comment by prakhar1989** [comment]
You forgot to commit the unittest file :stuck_out_tongue:

**Comment by vedangmehta** [comment]
Oops! Is it okay now?

**Comment by prakhar1989** [comment]
Yup. BTW, if you can do a git add, git commit, and git push the new file will start showing in the very same PR. You are not required to keep opening new ones. I'll merge this for now. Keep that in your mind for later :wink:

**Comment by vedangmehta** [comment]
Thanks a lot. Actually, I'm novice to opensource and VCS. Sorry for all the hassle! :)

**Comment by prakhar1989** [comment]
No worries at all. That's how we all start :+1: 

Looking forward to more of your PRs!

**Comment by vedangmehta** [comment]
:smiley:

**Pull request merged**
