### PR TITLE
Added Hierholzer's algorithm to find Eulerian Tour in a graph.

### PR DESCRIPTION
**Pull request by viiicky**
This program finds an Eulerian Tour in the given graph. The program is based on Hierholzer's algorithm. You can read about this algorithm at https://en.wikipedia.org/wiki/Eulerian_path

### CODE REVIEW

**Comment by prakhar1989** [comment]
Thanks for the PR @viiicky. I'm travelling right now.. give me a couple of days - I'll check this out and get back to you.

**Comment by viiicky** [comment]
@prakhar1989 Very fine.

**Comment by prakhar1989** [comment]
@viiicky I'm merging this for now. I'd like to do a few changes - such as using the `Graph` class used in other graph algorithms and add tests. But I'll do that myself in a couple of days.

Thanks for sending this PR :+1:

**Comment by viiicky** [comment]
Feel free to modify it. However, once you push the changes, please notify me. I would like to read that.

**Pull request merged**
