### PR TITLE
Create gcd_test.py

### PR DESCRIPTION
**Pull request by vedangmehta**
Unit test for GCD.py

### CODE REVIEW

**Comment by prakhar1989** [comment]
I did not knew until now that there exists a `fractions.gcd` method in the python stdlib!

**Comment by vedangmehta** [comment]
Only if there existed another language with such a feature rich standard library!

**Comment by prakhar1989** [comment]
Golang - https://golang.org/pkg/math/big/#Int.GCD :grin:

**Comment by vedangmehta** [comment]
Actually, C++ too has GCD function in it's algorithm library, but I feel that Python's standard library is one of the richest that we've got.

**Comment by vedangmehta** [comment]
Both the files are okay now, right?

**Comment by prakhar1989** [comment]
Yeah.. merging these for now. Next time, send bundle it all up in one PR :)

**Comment by vedangmehta** [comment]
I still can't figure out how to create a single pull request for two files in separate branches. Is there any good reference for this?

**Comment by prakhar1989** [comment]
Why are you using two separate branches for this? Just add the new code in one branch (e.g. master), add the files , commit and send PR. If you **DO** need two branches, then before sending the PR merge them locally and then send a PR.

**Comment by vedangmehta** [comment]
I'll keep that in mind.

**Pull request merged**
