### PR TITLE
Created simple setup.py so I could use union_find package

### PR DESCRIPTION
**Pull request by wandaboyer**
I wrote a simple setup.py program based on this [quickstart guide](http://the-hitchhikers-guide-to-packaging.readthedocs.org/en/latest/quickstart.html), which required that I add a README.txt file with the same content as your README.md (I don't believe that the markdown files can be read by the method called), and that I tag the current build as 'v1.0'. I successfully installed the union_find package and was able to use it in my work :+1:  :D Hopefully, this fork will give an basis for how to use setup.py, and will allow others to include more of the project's packages if desired. Thank you for this excellent project!

### CODE REVIEW

**Comment by prakhar1989** [comment]
Hi Wanda,

Thanks for the PR! Although the `setup.py` looks useful, I would like to keep this repository just as a storehouse of various algorithms. Since it's in Python, it is very straightforward to use these algorithms in your personal projects if you so desire. Adding python packages for each implementation would unnecessary blow up the repo size and make it hard to manage. More importantly, most implementations in this repo are primarily for learning and not exactly suited for production use. Hence, I'm not very keen on making this a library.

I hope that makes sense.  

Cheers :beers:

**Comment by wandaboyer** [comment]
Ahhh, gotcha!! That's a really good point... Thanks for the note, and again for the excellent project!

If there's any other way I can help out, don't hesitate to ask. Have a great night :D

Wanda B. Boyer

**Comment by prakhar1989** [comment]
Thanks Wanda! If you want to help out - just report any bugs that you encounter while using various algorithms in this repository. For extra brownie :cake: points you can also send in PR with an implementation of a new algorithm / data structure. :grinning:

**Comment by wandaboyer** [comment]
Sounds great! Everything's worked smoothly so far for me, so I'll look more into implementing and testing new material. Those brownie points do sure sound yummy! 🍰🍫🍦🍪🍩😋 Thanks again 😸

Wanda B. Boyer

**Pull request closed without merging**
