### PR TITLE
Binary search

### PR DESCRIPTION
**Pull request by SanketDG**
A simple iterative binary search algorithm.

Please review. I know I didn't update my fork but can you please merge this by resolving the merge conflicts?

Thank you.

### CODE REVIEW

**Comment by SanketDG** [comment]
Ping. Will you merge this?

**Comment by SanketDG** [comment]
Ping. I will probably close this if this won't be merged.

**Comment by prakhar1989** [comment]
Sorry.. this fell through the cracks. Can you resolve the merge conflict and resent the PR?

**Comment by SanketDG** [comment]
Done. Please review.

**Pull request merged**
